### ISSUE TITLE
Bug: cannot use '=' in `git config` commands.

### ISSUE THREAD

**Issue by dishb** [mvllow/dots#7]
## Issue:
In [this](https://github.com/mvllow/dots/wiki/Signing-git-commits#with-ssh) wiki page, you use the equals sign (=) to configure values with `git config`. This doesn't work.

These are the commands provided in the wiki page:
```
git config --global commit.gpgsign = true
git config --global user.name = <your name>
git config --global user.email = <your email>
git config --global user.signingKey = ~/.ssh/id_ed25519.pub
git config --global gpg.format = ssh
```

This is what they should be:
```
git config --global commit.gpgsign true
git config --global user.name <your name>
git config --global user.email <your email>
git config --global user.signingKey ~/.ssh/id_ed25519.pub
git config --global gpg.format ssh
```

## Specs:
- macOS 12.6.7
- git 2.41.0

**Comment by mvllow** [comment]
Good catch! Fixed & thank you :)
